### ISSUE TITLE
when I install,I met error like this picture,I want to ask how  can I do.

### ISSUE THREAD

**Issue by nyj123** [jaspershen/MetNormalizer#3]
![image](https://user-images.githubusercontent.com/61054316/112751031-52e2ea00-8ffe-11eb-9c32-75d721b30a86.png)
the demodata!
Thanks a lot!

**Comment by nyj123** [comment]
And I use the windows 10
Thanks a lot!

**Comment by jaspershen** [comment]
Sorry for the late reply. I just saw your message. I am not sure why it failed. If you are in China, try to install this from gitee. 
remotes::install_git("https://gitee.com/jaspershen/demoData")

**Comment by nyj123** [comment]
Thanks for your advice!
I install it successfully just now!
